runtime: python37 # or another supported version

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /static
  static_dir: static

- url: /.*
  script: auto
  secure: always
  

# libraries:
# - name: django_otp
#   version: "1.0.2"
