# Generated by Django 3.1.4 on 2021-07-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('picture', models.ImageField(default='anc.jpeg', upload_to='')),
                ('short_description', models.CharField(default='', max_length=600)),
                ('complete_description', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
