# Generated by Django 3.1.4 on 2021-01-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210101_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
