# Generated by Django 3.1.4 on 2021-08-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210730_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='conductor_crosssectional_area',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tower',
            name='conductor_length',
            field=models.CharField(default='', max_length=200),
        ),
    ]
