# Generated by Django 3.1.4 on 2021-01-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210101_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('picture', models.ImageField(default='male.png', upload_to='')),
                ('designation', models.CharField(default='', max_length=400)),
                ('description', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='picture',
            field=models.ImageField(default='male.png', upload_to=''),
        ),
    ]
