# Generated by Django 3.1.4 on 2021-01-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210101_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='linkedinprofile',
            field=models.CharField(default='https://www.linkedin.com/company/al-nafi', max_length=400),
        ),
    ]
