# Generated by Django 3.1.4 on 2021-01-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_team_linkedinprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='team',
            name='complete_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
