# Generated by Django 3.1.4 on 2021-08-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210801_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='cable_system',
            field=models.CharField(blank=True, choices=[('2 cable single phase', '2 cable single phase')], default='', max_length=200),
        ),
    ]
