# Generated by Django 3.1.4 on 2021-01-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210101_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='complete_description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
