# Generated by Django 3.1.4 on 2021-08-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_tower_cable_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tower',
            name='cable_system',
        ),
        migrations.AddField(
            model_name='tower',
            name='cable_configuration',
            field=models.CharField(blank=True, choices=[('horizontal', 'horizontal'), ('vertical', 'vertical')], default='', max_length=200),
        ),
    ]
