# Generated by Django 3.1.4 on 2021-01-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210101_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=150)),
                ('Last_Name', models.CharField(max_length=150)),
                ('Business_Email', models.CharField(max_length=50)),
                ('What_Are_You_Interested_In', models.CharField(max_length=50)),
                ('How_Can_We_Help_You', models.CharField(max_length=400)),
            ],
        ),
    ]
