# Generated by Django 3.1.4 on 2021-08-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210801_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tower',
            old_name='spacing_between_bundles_conductors',
            new_name='spacing_between_bundled_conductors',
        ),
    ]
