# Generated by Django 3.1.4 on 2021-08-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210801_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='spacing_between_conductors',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
