# Generated by Django 3.1.4 on 2021-01-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='complete_description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='service',
            name='complete_description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(default='', max_length=600),
        ),
    ]
