# Generated by Django 3.1.4 on 2021-08-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_tower_spacing_between_conductors'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='efficiency',
            field=models.CharField(blank=True, choices=[('horizontal', 'horizontal'), ('vertical', 'vertical')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tower',
            name='power_received_at_load_in_kVA',
            field=models.CharField(blank=True, choices=[('horizontal', 'horizontal'), ('vertical', 'vertical')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tower',
            name='power_transmitted_in_kVA',
            field=models.CharField(blank=True, choices=[('horizontal', 'horizontal'), ('vertical', 'vertical')], default='', max_length=200),
        ),
    ]
