# Generated by Django 3.1.4 on 2021-01-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210106_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(default='', max_length=300)),
                ('tool_name', models.CharField(default='', max_length=300)),
                ('package_description', models.CharField(default='', max_length=2000)),
                ('source', models.CharField(default='', max_length=200)),
                ('author', models.CharField(default='', max_length=200)),
                ('license', models.CharField(default='', max_length=200)),
                ('code', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
