# Generated by Django 3.1.4 on 2021-01-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='code',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
