# Generated by Django 3.1.4 on 2021-08-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20210801_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tower',
            name='power_received_at_load_in_kVA',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='power_transmitted_in_kVA',
        ),
        migrations.AddField(
            model_name='tower',
            name='power_received_at_load_in_MVA',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tower',
            name='power_transmitted_in_MVA',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tower',
            name='efficiency',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
