# Generated by Django 3.1.4 on 2021-01-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20210106_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='usage_code',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='packages',
            name='code',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
