# Generated by Django 3.1.4 on 2021-08-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20210801_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='voltage_regulation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
