# Generated by Django 3.1.4 on 2021-08-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_tower_voltage_regulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='receiving_end_voltage',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tower',
            name='sending_end_voltage',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
