# Generated by Django 3.1.4 on 2021-01-30 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20210130_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='short_description',
            new_name='short_descriptio',
        ),
    ]
