# Generated by Django 3.1.4 on 2021-08-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20210801_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tower',
            old_name='receiving_end_voltage',
            new_name='receiving_end_voltage_in_KV',
        ),
        migrations.RenameField(
            model_name='tower',
            old_name='sending_end_voltage',
            new_name='sending_end_voltage_in_KV',
        ),
    ]
