# Generated by Django 3.1.4 on 2021-01-30 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20210130_0554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='short_descriptio',
            new_name='short_description',
        ),
    ]
