# Generated by Django 3.1.4 on 2021-08-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_tower_corona_losses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tower',
            name='conductor_type',
            field=models.CharField(blank=True, choices=[('Aluminum Conductor Steel Reinforced (ACSR)', 'Aluminum Conductor Steel Reinforced (ACSR)'), ('All Aluminium conductors (AAC)', 'All Aluminium conductors (AAC)'), ('Aluminium conductor, Alloy-Reinforced (ACAR)', 'Aluminium conductor, Alloy-Reinforced (ACAR)')], default='', max_length=200),
        ),
    ]
