# Generated by Django 3.1.4 on 2021-01-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20210130_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('picture', models.ImageField(default='anc.jpeg', upload_to='')),
                ('short_description', models.CharField(default='', max_length=600)),
                ('complete_description', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='IS_Consultancy_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('picture', models.ImageField(default='anc.jpeg', upload_to='')),
                ('short_description', models.CharField(default='', max_length=600)),
                ('complete_description', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='IS_Security_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('picture', models.ImageField(default='anc.jpeg', upload_to='')),
                ('short_description', models.CharField(default='', max_length=600)),
                ('complete_description', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Software_Solutions_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('picture', models.ImageField(default='anc.jpeg', upload_to='')),
                ('short_description', models.CharField(default='', max_length=600)),
                ('complete_description', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
