# Generated by Django 3.1.4 on 2021-02-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_audit_service_is_consultancy_service_is_security_service_software_solutions_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='complete_description',
        ),
        migrations.AlterField(
            model_name='team',
            name='short_description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
