# Generated by Django 3.1.4 on 2021-02-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20210224_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='domain_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_description',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='packages',
            name='source',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='packages',
            name='usage_code',
            field=models.CharField(default='', max_length=4000),
        ),
    ]
