# Generated by Django 3.1.4 on 2021-02-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20210228_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='What_Are_You_Interested_In',
        ),
        migrations.AddField(
            model_name='contact',
            name='Contact_Number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
