# Generated by Django 3.1.4 on 2021-08-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_tower_insulator_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tower',
            name='line_type',
            field=models.CharField(blank=True, choices=[('SINGLE CIRCUIT UNBUNDLED', 'SINGLE CIRCUIT UNBUNDLED'), ('DOUBLE CIRCUIT UNBUNDLED', 'DOUBLE CIRCUIT UNBUNDLED'), ('DOUBLE CIRCUIT BUNDLED (2C)', 'DOUBLE CIRCUIT BUNDLED (2C)'), ('DOUBLE CIRCUIT BUNDLED (3C)', 'DOUBLE CIRCUIT BUNDLED (3C)'), ('DOUBLE CIRCUIT BUNDLED (4C)', 'DOUBLE CIRCUIT BUNDLED (4C)')], default='', max_length=200),
        ),
    ]
